#include <json_backbone/container_dbl.hpp>
#include <json_backbone/container_l_dbl.hpp>
#include <json_backbone/container_ll_ldbl.hpp>

#include <json_backbone/container_u.hpp>
#include <json_backbone/container_dbl_u.hpp>
#include <json_backbone/container_l_dbl_u.hpp>
#include <json_backbone/container_ll_ldbl_u.hpp>

#include <json_backbone/externalize.hpp>
#include <json_backbone/extensions/boost_spirit_json/json.hpp>
#include <json_backbone/extensions/boost_spirit_json/externalize_json.hpp>

JSON_BACKBONE_INSTANTIATE(JSON_BACKBONE_CONTAINER_DBL_SIGNATURE());
JSON_BACKBONE_INSTANTIATE(JSON_BACKBONE_CONTAINER_L_DBL_SIGNATURE());
JSON_BACKBONE_INSTANTIATE(JSON_BACKBONE_CONTAINER_LL_LDBL_SIGNATURE());

JSON_BACKBONE_INSTANTIATE(JSON_BACKBONE_CONTAINER_U_SIGNATURE());
JSON_BACKBONE_INSTANTIATE(JSON_BACKBONE_CONTAINER_DBL_U_SIGNATURE());
JSON_BACKBONE_INSTANTIATE(JSON_BACKBONE_CONTAINER_L_DBL_U_SIGNATURE());
JSON_BACKBONE_INSTANTIATE(JSON_BACKBONE_CONTAINER_LL_LDBL_U_SIGNATURE());

JSON_BACKBONE_INSTANTIATE_JSON(JSON_BACKBONE_CONTAINER_DBL_SIGNATURE());
JSON_BACKBONE_INSTANTIATE_JSON(JSON_BACKBONE_CONTAINER_L_DBL_SIGNATURE());
JSON_BACKBONE_INSTANTIATE_JSON(JSON_BACKBONE_CONTAINER_LL_LDBL_SIGNATURE());

JSON_BACKBONE_INSTANTIATE_JSON(JSON_BACKBONE_CONTAINER_U_SIGNATURE());
JSON_BACKBONE_INSTANTIATE_JSON(JSON_BACKBONE_CONTAINER_DBL_U_SIGNATURE());
JSON_BACKBONE_INSTANTIATE_JSON(JSON_BACKBONE_CONTAINER_L_DBL_U_SIGNATURE());
JSON_BACKBONE_INSTANTIATE_JSON(JSON_BACKBONE_CONTAINER_LL_LDBL_U_SIGNATURE());
