#include <nested_container/container_dbl.hpp>
#include <nested_container/container_l_dbl.hpp>
#include <nested_container/container_ll_ldbl.hpp>

#include <nested_container/container_u.hpp>
#include <nested_container/container_dbl_u.hpp>
#include <nested_container/container_l_dbl_u.hpp>
#include <nested_container/container_ll_ldbl_u.hpp>

#include <nested_container/externalize.hpp>
#include <nested_container/extensions/boost_spirit_json/json.hpp>
#include <nested_container/extensions/boost_spirit_json/externalize_json.hpp>

NESTED_CONTAINER_INSTANTIATE(NESTED_CONTAINER_CONTAINER_DBL_SIGNATURE());
NESTED_CONTAINER_INSTANTIATE(NESTED_CONTAINER_CONTAINER_L_DBL_SIGNATURE());
NESTED_CONTAINER_INSTANTIATE(NESTED_CONTAINER_CONTAINER_LL_LDBL_SIGNATURE());

NESTED_CONTAINER_INSTANTIATE(NESTED_CONTAINER_CONTAINER_U_SIGNATURE());
NESTED_CONTAINER_INSTANTIATE(NESTED_CONTAINER_CONTAINER_DBL_U_SIGNATURE());
NESTED_CONTAINER_INSTANTIATE(NESTED_CONTAINER_CONTAINER_L_DBL_U_SIGNATURE());
NESTED_CONTAINER_INSTANTIATE(NESTED_CONTAINER_CONTAINER_LL_LDBL_U_SIGNATURE());

NESTED_CONTAINER_INSTANTIATE_JSON(NESTED_CONTAINER_CONTAINER_DBL_SIGNATURE());
NESTED_CONTAINER_INSTANTIATE_JSON(NESTED_CONTAINER_CONTAINER_L_DBL_SIGNATURE());
NESTED_CONTAINER_INSTANTIATE_JSON(NESTED_CONTAINER_CONTAINER_LL_LDBL_SIGNATURE());

NESTED_CONTAINER_INSTANTIATE_JSON(NESTED_CONTAINER_CONTAINER_U_SIGNATURE());
NESTED_CONTAINER_INSTANTIATE_JSON(NESTED_CONTAINER_CONTAINER_DBL_U_SIGNATURE());
NESTED_CONTAINER_INSTANTIATE_JSON(NESTED_CONTAINER_CONTAINER_L_DBL_U_SIGNATURE());
NESTED_CONTAINER_INSTANTIATE_JSON(NESTED_CONTAINER_CONTAINER_LL_LDBL_U_SIGNATURE());
